Dev ag sp 10
SocialGouv/eMJPM-api pull request #142
Opened 2019-01-15 16:08 UTC by gonzalezad1

2019-01-31 17:44 UTC, douglasduteil requested changes

2019-01-31 17:44 UTC, douglasduteil commented on routes/codePostaux.js
> + * /mandataires/1/commentaires:
The url is `mandataires/1/commentaires` ?

2019-01-31 17:44 UTC, douglasduteil commented on routes/codePostaux.js
> + *     produces:
There are no comments here ...

2019-01-31 17:44 UTC, douglasduteil commented on routes/codePostaux.js
> + *         description: Return all commentaires of one mandataire
It returns post codes right ?

2019-01-31 17:44 UTC, douglasduteil commented on routes/index.js
> +router.use("/codePostaux", require("./codePostaux"));
\cc @revolunet 
I'm not sure case sensitive urls is a good idea for an api

2019-01-31 17:44 UTC, douglasduteil commented on routes/tis.js
> +  addMandataireTis(req.body.ti_id, mandataire.id)
Could be

```js
await addMandataireTis(req.body.ti_id, mandataire.id);
const tis = await getAllTisByMandataire(mandataire.id)
// etc...
```

2019-02-01 15:30 UTC, revolunet commented
Vérifier pourquoi on a des `Empty .update() call detected` dans le log des tests

2019-02-07 13:40 UTC, revolunet requested changes

2019-02-07 13:40 UTC, revolunet commented on db/queries/users.js
> +  getSpecificUser
a priori `user` n'est utilisé que dans routes/admin.js.
il faudrait supprimer cette methode au profit d'une méthode `getUser` ?

2019-02-07 13:43 UTC, revolunet commented on db/queries/mandataires.js
> +  getCoordonneesByPostCode
dans `getCoordonneesByPostCode`, le paramètre est `userId`. normal ?

2019-02-07 14:32 UTC, revolunet approved these changes

2019-02-07 14:33 UTC, merged